{% set name = "camply" %}
{% set version = "0.1.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: e26700ebf0e792a85241188d95aeea0dad30acb46313b6e062247c524b6797de

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.utils.camply_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - python-dotenv
    - pytz
    - pyyaml
    - requests
    - tenacity

test:
  imports:
    - camply
    - camply.config
    - camply.notifications
    - camply.providers
    - camply.providers.xanterra
    - camply.providers.recreation_dot_gov
    - camply.search
    - camply.utils
  commands:
    - pip check
    - camply --help
  requires:
    - pip

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - thewchan
