{% set name = "camply" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: 012463349254ed11624fcc9a5c176949b67718d06db3460b42a3348a9bfbc64f

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.utils.camply_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.10
  run:
    - pandas
    - python >=3.6,<3.10
    - python-dotenv
    - pytz
    - requests
    - tenacity

test:
  imports:
    - camply
    - camply.config
  commands:
    - pip check
    - camply --help
  requires:
    - pip

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - thewchan
